### ISSUE TITLE
I want to connect Arduino Mega [4 pins / stepper / per axis] (look image) how ?!!!

### ISSUE THREAD

**Issue by savosik** [carlosgs/grblForCyclone#2]
![untitled-2](https://cloud.githubusercontent.com/assets/16825666/23376915/fc1dd992-fd3e-11e6-886b-489f38e5d530.jpg)

**Comment by CarlosGS** [comment]
In order to drive stepper motors you need to use a driver, such as the Pololu A4988 or the "stepstick" version. The diagram you have shown could also work but the GRBL firmware is not prepared to drive the motor coils directly.
