### ISSUE TITLE
400 steps Stepper Motor support?

### ISSUE THREAD

**Issue by bmanos** [carlosgs/grblForCyclone#5]
Hello,
I would like to use 400 steps stepper motors (because I have them) 

Specifications:
Step Angle (degrees) : 0.9
2-Phase (4 wires)
Rated Voltage: 3V
Rated Current: 1.7A/Phase
5mm Diameter Drive Shaft
Holding Torque: 48N.cm - 4.8kg.cm
NEMA 17 form factor
datasheet link: http://dlnmh9ip6v2uc.cloudfront.net/datasheets/Robotics/42BYGHM809.PDF

How can I configure them to work?

Thanks in advance
Emmanuel

**Comment by CarlosGS** [comment]
It depends on the version of GRBL that you are using, and whether it is a RAMPS of a Sanguinololu board.
Check out the GRBL manual to see if it helps: https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9#100-101-and-102--xyz-stepsmm

**Comment by bmanos** [comment]
Thanks for the quick response
I use the RAMPS with A4988 driver and I also use the your file https://github.com/carlosgs/grblForCyclone/archive/grblForCyclone.zip
Should I modify the "defaults.h"? and what should I change? a little help is very welcome
Thanks

**Comment by CarlosGS** [comment]
Yes, I think you should change STEPS_PER_REV almost at the bottom of the defaults.h

Then follow these instructions: https://github.com/CarlosGS/grblForCyclone#how-to-flash-the-grbl-firmware

Let me know of the outcome!

**Comment by bmanos** [comment]
Thanks I already did this without success but I clear the eeprom first and now it works. The only problem now is the speed it moves quicker than before (how can I change this)
Thanks one more time

**Comment by CarlosGS** [comment]
Please first check that the performed distances are accurate.

**Comment by bmanos** [comment]
The distance for Y is ok :101 and for X is 161 instead of 168.
I also correct those values inside the defaults.h file.

**Comment by CarlosGS** [comment]
Then it looks fine. The motion speed can be adjusted in the host software. Are you using bCNC?

**Comment by bmanos** [comment]
yes just first steps still looking for what is where

**Comment by CarlosGS** [comment]
Awesome, bCNC is the option that I prefer. Have you seen this tutorial? https://github.com/CarlosGS/grblForCyclone/wiki/1)-Configure-bCNC-for-Cyclone

**Comment by CarlosGS** [comment]
Sorry this is the right tutorial page: https://github.com/carlosgs/grblForCyclone/wiki/2%29-Hello-World!-Mill-a-bowl-with-bCNC

**Comment by bmanos** [comment]
Hi Carlos,
yes I have seen it and I will try it next week end.
Where can I found infos on adding z end stop and for the probes usage.
Is there any other tutorial from start to finish on how to design export and mill a pcb board?
Thanks again, Emmanuel

**Comment by CarlosGS** [comment]
Not that I can think of. Give a try to the search option of the Cyclone mail list: https://groups.google.com/group/cyclone-pcb-factory
I have not used the machine for a long time so there are some things I don't remember too well..

And good luck with the tests! Feel free to share your results in the mail list as there is more people that can help.
