### ISSUE TITLE
Port to another Board like GT2560

### ISSUE THREAD

**Issue by fsk25** [carlosgs/grblForCyclone#7]
Hello, is it possible to reassign the pins of the Arduino to other functions? I have an old GT2560 and try to get it run. Essentially it is a ramps board with a different pin assignment. Is there something like the pins.h from the marlin firmware in your code?

**Comment by CarlosGS** [comment]
Yep! Have a look at https://github.com/CarlosGS/grblForCyclone/blob/grblForCyclone/cpu_map.h#L468

**Comment by fsk25** [comment]
Pretty cool. It works. You made my day!

**Comment by CarlosGS** [comment]
Fantastic! you made mine :-)
